services:
  crafty:
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    container_name: crafty
    environment:
      TZ: ${TZ}
    volumes:
      - /data/appdata/crafty/backups:/crafty/backups
      - /data/appdata/crafty/logs:/crafty/logs
      - /data/appdata/crafty/servers:/crafty/servers
      - /data/appdata/crafty/config:/crafty/app/config
      - /data/appdata/crafty/import:/crafty/import
    ports:
      - "${CRAFTY_PANEL_PORT}:8443"
      # Expose a default Minecraft port (you can also use Crafty's port range approach)
      - "${MC_PORT}:${MC_PORT}/tcp"
    restart: unless-stopped
